### ISSUE TITLE
what is  means of the  accelerator data?

### ISSUE THREAD

**Issue by chao-sun01io** [juchong/ADIS16485-Arduino-Teensy#1]
I use your great job to grab data from  adis16485,and when I read Proc_id register I can get a return value as 16485. 
when I print the accelerator data, I notice that the acceleration of z is always about 1, does it is normalized by  gravitational acclebration g(9.8...)? 

Thank you for your kind help.

**Comment by juchong** [comment]
Hi,
This is not an issue. The accelerometers in the IMU read acceleration. In this case, they read gravity (1g).
