### ISSUE TITLE
Is it possible to send data at a frequency of 100+ Hz on ardiuno mega2560?

### ISSUE THREAD

**Issue by chao-sun01io** [juchong/ADIS16485-Arduino-Teensy#2]
I am trying to send data by serial to PC then advertise it as ROS topic(sensor_msgs/Imu) , is it possibale to send data at a  frequency of 100+ Hz. Btw, did you try to do such job before? Thanks

**Comment by juchong** [comment]
It is possible to adjust the sample frequency using the DEC_RATE register. Please refer to the datasheet for details.

**Comment by chao-sun01io** [comment]
Thanks ! I will look up the datasheet
